---
- name: "Install python"
  become: true
  apt:
    name: python3
    state: latest
    update_cache: "yes"

- name: "wait 600 seconds for target connection to become reachable/usable."
  wait_for_connection:
    timeout: 600
    
- name: "Update/upgrade packages"
  become: true
  apt:
    update_cache: "yes"
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: "pm2"
    global: true
    production: true
    state: present